# -*- coding: utf-8 -*-
"""별찍기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZPqluRpf_DgtaT8MSjIhWs7M5P1feXu
"""

j = 0
k = 5
while j < k :
    j += 1
    print("*" * j)

j = 0
k = 6
while j < k :
    j += 1
    print("*" * (k-j))

for i in range(1, 6):
  print("*"*i)

for i in range(1,6):
  print("*" *(6-i))

