# -*- coding: utf-8 -*-
"""구구단.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bB_1ndwLsPYEpT8hjJwFu5dwc4CyACwU
"""

print("구구단 출력\n")

for i in range(1,10):
  print(f"{i}\t", end="")
  for j in range(2,10):
    print(i*j, end=" ")
  print("\n")

print("구구단 출력\n")

for i in range(1,10):
  print(f"{i}\t", end="")
  for j in range(2,10):
    print(i*j, end="\t")
  print("\n")

