# -*- coding: utf-8 -*-
"""짝수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AzJbn1M-H_zE2Atl24kpr7yGfKPrgxMX
"""

#for문 이용

print("1부터 10까지의 짝수를 표시합니다.")
for i in range(2,11,2):
  print(i)

#if for

print("1부터 10까지의 짝수를 표시합니다.")
for i in range(1,11):
  if i%2 == 0:
    print(i)

