# -*- coding: utf-8 -*-
"""230809_연습문제4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LN1lnMnwLDzc_dX3WQWgkCah2SjXVCVH

연습문제4. 리스트에서 짝수 홀수 구분하기
"""

numbers = [1,2,3,4,5,6,7,8,9,10]

#for문과 if문을 사용하여 짝수와 홀수 분리하기
even_numbers=[]
odd_numbers=[]


#이 사이에 코드를 채워보자

for i in numbers:
  if i%2 == 0:
    even_numbers.append(i)
  else :
    odd_numbers.append(i)

#이 사이에 코드를 채워보자


#결과출력
print("짝수:", even_numbers)    #출력 | 짝수: [2, 4, 6, 8, 10]
print("홀수:", odd_numbers)     #출력 | 홀수 : [1, 3, 5, 7, 9]

