# -*- coding: utf-8 -*-
"""230809_연습문제3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LN1lnMnwLDzc_dX3WQWgkCah2SjXVCVH

연습문제3. 리스트 내 중복 제거하기
"""

fruits = ['apple', 'banana', 'orange', 'banana', 'kiwi', 'apple']

#for문과 if문을 사용하여 중복 제거하기
unique_fruits=[]


#이 사이에 코드를 채워보자

for i in fruits:
  if i not in unique_fruits:
    unique_fruits.append(i)

#이 사이에 코드를 채워보자


#결과출력
print(unique_fruits)    #출력 | ['apple', 'banana', 'orange', 'kiwi']