# -*- coding: utf-8 -*-
"""230809_연습문제5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LN1lnMnwLDzc_dX3WQWgkCah2SjXVCVH

연습문제5. 리스트의 모든 요소 곱하기
"""

numbers = [1, 2, 3, 4, 5]

#for문을 사용하여 리스트의 모든 요소 곱하기
result=1


#이 사이에 코드를 채워보자

for i in numbers:
  result *= i

#이 사이에 코드를 채워보자


#결과 출력
print("곱셈결과:", result)    #출력 | 곱셈결과: 120

