# -*- coding: utf-8 -*-
"""0816과제_정해담.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gjbQH0FxXvvMtOAdwclXGnmcQ52efGK-

##정수 리스트를 입력받아, 그 중 짝수만을 반환하는 함수의 코드를 완성해보자
"""

#'even numbers' 함수를 정의합니다.
#이 함수는 정수 리스트를 입력받아 짝수만을 반환합니다.

def even_numbers(numbers):
  #이 곳에 코드를 작성해주세요
  even_list = [i for i in numbers if i % 2 == 0]
  return even_list
  #이 곳에 코드를 작성해주세요

#예제로 사용할 숫자 리스트
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]

#'even_numbers' 함수를 호출하고 결과를 출력합니다.
print(even_numbers(numbers))

"""##문자열을 입력받아서 그 문자열을 거꾸로 뒤집은 결과를 반환하는 함수를 완성해보자"""

# 'reverse_string' 함수를 정의합니다.
#이 함수는 문자열을 입력받아 거꾸로 뒤집은 결과를 반환합니다.

def reverse_string(s):
  # 이 곳에 코드를 작성해주세요
  r_string = s[::-1]
  return r_string
  # 이 곳에 코드를 작성해주세요

# 예제로 사용할 문자열
example_string = "파이썬"
# 'reverse_string' 함수를 호출하고 결과를 출력합니다.
print(reverse_string(example_string)) # 출력: "썬이파"

"""##리스트의 모든 요소를 더하는 함수를 완성해보자"""

# 'sum_elements' 함수를 정의합니다.
#이 함수는 리스트의 모든 요소를 더해 반환합니다.

def sum_elements(elements):
  # 이 곳에 코드를 작성해주세요
  for num in elements:
    sum_list  = sum(elements)
    return sum_list
  # 이 곳에 코드를 작성해주세요

# 예제로 사용할 리스트
numbers = [10, 20, 30, 40, 50]
 # 'sum_elements' 함수를 호출하고 결과를 출력합니다.
print(sum_elements(numbers)) # 출력: 150

"""##정수 리스트를 입력받아 그 중 가장 큰 수와 가장 작은 수를 반환하는 함수를 완성해보자"""

# 'find_max_min' 함수를 정의합니다.
#이 함수는 정수 리스트를 입력받아 가장 큰 수와 가장 작은 수를 반환합니다.

def find_max_min(numbers_list):
  # 이 곳에 코드를 작성해주세요
  max_value = max(numbers_list)
  min_value = min(numbers_list)
  return max_value, min_value
  # 이 곳에 코드를 작성해주세요

# 예제로 사용할 정수 리스트
numbers = [34, 12, 56, 78, 23]
# 'find_max_min' 함수를 호출하고 결과를 출력합니다.
print(find_max_min(numbers)) # 출력: (78, 12)

"""##문자열을 입력 받아서 그 중 영어 모음의 개수를 반환하는 함수를 완성하세요"""

# 'count_vowels' 함수를 정의합니다.
#이 함수는 문자열을 입력받아 모든 모음의 개수를 반환합니다.
def count_vowels(s):
  # 이 곳에 코드를 작성해주세요
  vowel_list = ['a','e','i','o','u','A','E','I','O','U']
  count_num = 0

  for i in s:
    if i in vowel_list:
      count_num += 1
  return count_num

  # 이 곳에 코드를 작성해주세요

# 예제로 사용할 문자열
string = "Hello, Python!"
# 'count_vowels' 함수를 호출하고 결과를 출력합니다.
print(count_vowels(string)) # 출력: 4

"""##문자열을 입력 받아서 알파벳의 빈도를 반환하는 함수를 완성하세요"""

# 'alphabet_frequency' 함수를 정의합니다.
#이 함수는 문자열을 입력받아 각 알파벳 문자의 빈도를 사전 형태로 반환합니다.
def alphabet_frequency(s):
  # 이 곳에 코드를 작성해주세요
  char_count = {}
  for char in s:
    if char.isalpha():
      if char in char_count:
        char_count[char] += 1
      else :
        char_count[char] = 1
  return char_count
  # 이 곳에 코드를 작성해주세요

# 예제로 사용할 문자열
string = "Hello, Python!"
# 'alphabet_frequency' 함수를 호출하고 결과를 출력합니다.
print(alphabet_frequency(string)) # 출력: {'H': 1, 'e': 1, 'l': 2, 'o': 2, 'P': 1, 'y': 1, 't': 1, 'h': 1, 'n': 1}

