# -*- coding: utf-8 -*-
"""230816_실습3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xMTzd77OyUJ8gq7LF-wAfIrfg9vbQCmZ

##리스트의 모든 요소를 더하는 함수를 완성해보자
"""

# 'sum_elements' 함수를 정의합니다.
#이 함수는 리스트의 모든 요소를 더해 반환합니다.

def sum_elements(elements):
  # 이 곳에 코드를 작성해주세요
  for num in elements:
    sum_list  = sum(elements)
    return sum_list
  # 이 곳에 코드를 작성해주세요

# 예제로 사용할 리스트
numbers = [10, 20, 30, 40, 50]
 # 'sum_elements' 함수를 호출하고 결과를 출력합니다.
print(sum_elements(numbers)) # 출력: 150

