# -*- coding: utf-8 -*-
"""230816_실습1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xMTzd77OyUJ8gq7LF-wAfIrfg9vbQCmZ

##정수 리스트를 입력받아, 그 중 짝수만을 반환하는 함수의 코드를 완성해보자
"""

#'even numbers' 함수를 정의합니다.
#이 함수는 정수 리스트를 입력받아 짝수만을 반환합니다.

def even_numbers(numbers):
  #이 곳에 코드를 작성해주세요
  even_list = [i for i in numbers if i % 2 == 0]
  return even_list
  #이 곳에 코드를 작성해주세요

#예제로 사용할 숫자 리스트
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]

#'even_numbers' 함수를 호출하고 결과를 출력합니다.
print(even_numbers(numbers))

