# -*- coding: utf-8 -*-
"""230816_실습5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xMTzd77OyUJ8gq7LF-wAfIrfg9vbQCmZ

##문자열을 입력 받아서 그 중 영어 모음의 개수를 반환하는 함수를 완성하세요
"""

# 'count_vowels' 함수를 정의합니다.
#이 함수는 문자열을 입력받아 모든 모음의 개수를 반환합니다.
def count_vowels(s):
  # 이 곳에 코드를 작성해주세요
  vowel_list = ['a','e','i','o','u','A','E','I','O','U']
  count_num = 0

  for i in s:
    if i in vowel_list:
      count_num += 1
  return count_num

  # 이 곳에 코드를 작성해주세요

# 예제로 사용할 문자열
string = "Hello, Python!"
# 'count_vowels' 함수를 호출하고 결과를 출력합니다.
print(count_vowels(string)) # 출력: 4

